services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

stages:
  - lint
  - test

lint:
  stage: lint
  image: python:3.8
  script:
    - pip install --upgrade pip
    - pip install flake8 black isort
    - black client/mainwindow.py
    - flake8 client/mainwindow.py
    - isort client/mainwindow.py

unit-test:
  stage: test
  image: python:3.8
  script:
    - pip install pytest
    - pytest tests/unit_test.py

integration-test:
  stage: test
  image: python:3.8
  script:
    - pip install pytest
    - pip install PyQt6
    - pip install werkzeug
    - pip install requests
    - apt-get update && apt-get install -y libgl1
    - apt-get update && apt-get install -y libxkbcommon0
    - apt-get install -y libegl1
    - apt-get install -y libdbus-1-3
    - export PYTHONPATH=$PYTHONPATH:/builds/swe/sose25/team14
    - export QT_QPA_PLATFORM=offscreen
    - pytest tests/integration_test.py || exit 1
